# Generated by Django 5.0.dev20230224125942 on 2023-02-27 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="dummy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "dummyfield",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cars.tires"
                    ),
                ),
                (
                    "m2mfield",
                    models.ManyToManyField(related_name="dummym2m", to="cars.tires"),
                ),
            ],
        ),
    ]
