# Generated by Django 5.0.dev20230224125942 on 2023-02-27 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("tires", "0001_initial"),
        ("tires", "0002_tires_alter_dummy_dummyfield_alter_dummy_m2mfield"),
    ]

    initial = True

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tires",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.TextField(max_length=10)),
                ("size", models.IntegerField(default=16)),
            ],
            options={
                "indexes": [],
                "constraints": [],
            },
            state_only_op=False,
        ),
        migrations.CreateModel(
            name="dummy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "dummyfield",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tires.tires"
                    ),
                ),
                (
                    "m2mfield",
                    models.ManyToManyField(
                        related_name="dummym2m", to="tires.tires"),
                ),
            ],
        ),
    ]
