# Generated by Django 5.0.dev20230224125942 on 2023-02-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ("cars", "0002_alter_tires_table"),
        ("tires", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tires",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.TextField(max_length=10)),
                ("size", models.IntegerField(default=16)),
            ],
            options={
                "indexes": [],
                "constraints": [],
            },
            state_only_op=True,
        ),
        migrations.AlterField(
            model_name="dummy",
            name="dummyfield",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tires.tires"
            ),
        ),
        migrations.AlterField(
            model_name="dummy",
            name="m2mfield",
            field=models.ManyToManyField(
                related_name="dummym2m", to="tires.tires"),
        ),
    ]
