# Generated by Django 5.0.dev20230224125942 on 2023-02-27 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        # ("cars", "0001_initial"),
        ("cars", "0002_alter_tires_table"),
        ("cars", "0003_alter_cars_tires_delete_tires"),
    ]

    initial = True

    dependencies = [
        # ("tires", "0002_tires_alter_dummy_dummyfield_alter_dummy_m2mfield"),
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=20)),
                ("model", models.CharField(max_length=10)),
                ("price", models.IntegerField(default=0)),
                (
                    "tires",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tires.tires"
                    ),
                ),
            ],
        ),
    ]
