# Generated by Django 5.0.dev20230224125942 on 2023-02-27 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # migrations.CreateModel(
        #     name="Tires",
        #     fields=[
        #         (
        #             "id",
        #             models.BigAutoField(
        #                 auto_created=True,
        #                 primary_key=True,
        #                 serialize=False,
        #                 verbose_name="ID",
        #             ),
        #         ),
        #         ("brand", models.TextField(max_length=10)),
        #         ("size", models.IntegerField(default=16)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name="Cars",
        #     fields=[
        #         (
        #             "id",
        #             models.BigAutoField(
        #                 auto_created=True,
        #                 primary_key=True,
        #                 serialize=False,
        #                 verbose_name="ID",
        #             ),
        #         ),
        #         ("name", models.TextField(max_length=20)),
        #         ("model", models.CharField(max_length=10)),
        #         ("price", models.IntegerField(default=0)),
        #         (
        #             "tires",
        #             models.ForeignKey(
        #                 on_delete=django.db.models.deletion.CASCADE, to="cars.tires"
        #             ),
        #         ),
        #     ],
        # ),
    ]
