# Generated by Django 5.0.dev20230224125942 on 2023-02-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tires", "0002_tires_alter_dummy_dummyfield_alter_dummy_m2mfield"),
        ("cars", "0002_alter_tires_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="tires",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tires.tires"
            ),
        ),
        migrations.DeleteModel(
            name="tires",
            state_only_op=True,
        ),
    ]
